name: events update

on:
  workflow_dispatch:
  schedule:
  - cron: 0 2 * * *

jobs:
  update-jobs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Update Jobs
      run: |
        sudo apt-get update && sudo apt-get install -y python3 python3-pip python3-setuptools wget
        sudo pip3 install -r scripts/requirements.txt
        python3 scripts/update_events.py

    # TODO automation to post updates 

    - name: Push Updates
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        printf "GitHub Actor: ${GITHUB_ACTOR}\n"

        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"

        git add calendars/*.ical

        set +e
        git status | grep modified
        if [ $? -eq 0 ]; then
            set -e
            printf "Changes\n"
            git commit -m "Automated push to update events $(date '+%Y-%m-%d')" || exit 0
            git push origin main
        else
            set -e
            printf "No changes\n"
        fi
